# Site settings
title: Shai Sachs
email:
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Shai Sachs. Includes blog posts, book reviews, and projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shaisachs.github.io" # the base hostname & protocol for your site

# User setting
owner: Shai Sachs
email:
facebook_username: shaisachs
twitter_username: shaisachs
github_username: shaisachs
telephone:
copyright: Shai Sachs

# API settings
google_api_key:

# Build settings
markdown: kramdown

collections:
  projects:
    order:
